name: Build and Deploy Docs
on:
  push:	
    branches:	
      - master
    paths:
    - 'docs/**'
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy Docs
      uses: testthedocs/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs/.vuepress/dist # The folder, the action should deploy.
        BUILD_SCRIPT: npm install && npm run docs:build # The build script the action should run prior to deploying.