name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node 12 sample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
        env:
          GQL_ENDPOINT: ${{secrets.GQL_ENDPOINT}}
          GQL_SECRET: ${{secrets.GQL_SECRET}}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Setup GIT
        run: |
          git config --global user.email "iam@spartak.io"
          git config --global user.name "Spartak"
      - name: Set version ${GITHUB_REF#"refs/tags/"}
        run: npm version ${GITHUB_REF#"refs/tags/"}
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}