name: Lint / Test / Coverage

on:
  push:
    branches-ignore:    
      - 'gh-pages'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run on node 12
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
          node-version: 12
    - run: npm install
    - run: npm test
      env:
        GQL_ENDPOINT: ${{secrets.GQL_ENDPOINT}}
        GQL_SECRET: ${{secrets.GQL_SECRET}}
        JWT_TOKEN: ${{secrets.JWT_TOKEN}}

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}