name: Test coverage

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node 12 sample
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
          node-version: 12
    - run: npm install
    - run: npm test
      env:
        GQL_ENDPOINT: ${{secrets.GQL_ENDPOINT}}
        GQL_SECRET: ${{secrets.GQL_SECRET}}
    - run: npm run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
