name: Test coverage

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12' ]
    name: Node ${{ matrix.node }} sample
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm test
      env:
        GQL_ENDPOINT: ${{secrets.GQL_ENDPOINT}}
        GQL_SECRET: ${{secrets.GQL_SECRET}}

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
